---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: "{{cloud_name}}"
    server: "{{ item.value | json_query('name') }}"
  loop: "{{osp_servers|dict2items}}"
  register: server_status

- name: Get Instance names
  set_fact:
    server_names: "{{server_status | json_query(name_query)}}"
  vars:
    name_query: "results[].openstack_servers[].name"

- name: Delete instances
  os_server:
    name: "{{item}}"
    cloud: "{{cloud_name}}"
    state: absent
  loop: "{{server_names}}"   
