- name: Playbook for Testing 3-Tier app on RHOSP
  hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Get frontend public IPv4
    set_fact:
      frontend_ipv4: "{{openstack_info | json_query('ansible_facts.openstack_servers[].public_v4') | first}}"

  - name: Curl website
    uri:
      url: "http://{{frontend_ipv4}}"
      method: GET
      return_content: yes
    with_sequence: start=0 end=1
    register: webpage

  - name: Print results
    debug:
      msg: "{{webpage}}"

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when:
      - "'Ansible has done its job' not in webpage.results[0].content"
      - "'Ansible has done its job' not in webpage.results[1].content"
    tags:
      - osp.smoke
